Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -1,15 +1,14 @@
 name: test
 
 on:
-  push:
-    tags:
-      - '*'
+  # push:
+  #   tags:
+  #     - '*'
   workflow_dispatch:
     inputs:
-      status:
-        description: 'status of do something'
-        type: number
-        default: 0
+      env:
+        description: 'Env'
+        type: environment
 
 jobs:
   TEST:
@@ -19,6 +18,9 @@ jobs:
       TARGET_ID: ${{ env.ID }}
     runs-on: ubuntu-latest
     steps:
+      - name: Echo NAME1
+        run: |
+          echo "Name1 is: ${{ vars.NAME1 }}
       # - name: Checkout
       #   uses: actions/checkout@v4
       #   with:
@@ -32,26 +34,26 @@ jobs:
       # - name: Print the tag
       #   run: |
       #     echo "Tag is: ${{ steps.get_tag.outputs.tag }}"
-      - name: Do something
-        id: dosomething
-        continue-on-error: true
-        run: |
-          echo "Value of TARGET_ID: ${{ env.TARGET_ID }}"
-          exit ${{ inputs.status }}
+      # - name: Do something
+      #   id: dosomething
+      #   continue-on-error: true
+      #   run: |
+      #     echo "Value of TARGET_ID: ${{ env.TARGET_ID }}"
+      #     exit ${{ inputs.status }}
 
-      - name: Handle OK
-        if: steps.dosomething.outcome == 'success'
-        run: |
-          echo "ID=2" >> $GITHUB_ENV
-          echo "STATUS=OK" >> $GITHUB_ENV
-      - name: Hanle NOT OK
-        if: steps.dosomething.outcome == 'failure'
-        run: |
-          echo "ID=1" >> $GITHUB_ENV
-          echo "STATUS=NOT OK" >> $GITHUB_ENV
-      - name: Update something
-        run: |
-          echo "ID is: ${{ env.ID }} , STATUS: ${{ env.STATUS }}"
+      # - name: Handle OK
+      #   if: steps.dosomething.outcome == 'success'
+      #   run: |
+      #     echo "ID=2" >> $GITHUB_ENV
+      #     echo "STATUS=OK" >> $GITHUB_ENV
+      # - name: Hanle NOT OK
+      #   if: steps.dosomething.outcome == 'failure'
+      #   run: |
+      #     echo "ID=1" >> $GITHUB_ENV
+      #     echo "STATUS=NOT OK" >> $GITHUB_ENV
+      # - name: Update something
+      #   run: |
+      #     echo "ID is: ${{ env.ID }} , STATUS: ${{ env.STATUS }}"
       # - uses: olegtarasov/get-tag@v2.1.3
       #   id: tagName
 
